### ISSUE TITLE
Installation problems on raspberry pi with python3

### ISSUE THREAD

**Issue by EagleAdam** [djax666/mystrombutton2mqtt#4]
I tried to install this on a Raspberry Pi running Rasbian Buster. I installed Python3 and pip3 but that's about it on this raspberry pi.

The settings file was modified to include my buttons, but as I don't have any "plus" buttons, I left that section as is in the sample:

When I tried to run the python command, I got this error:
```
pi@TEST:~/mystrombutton2mqtt $ python3 mystrombutton2mqtt.py ./resources/settings.json
Traceback (most recent call last):
  File "mystrombutton2mqtt.py", line 256, in <module>
    if LEVEL[mac.upper()] == None:
KeyError: '3423456789AB'
```
The only way I could find to fix this was removing the if statement completely from the code. I'm not really a coder so not sure why this doesn't work on a RPI...

**Comment by djax666** [comment]
Thank you for your feedback. I fix the issue in the release 1.3.1. You can remove the section "button+" from the settings.json if you don't need it.
